services:
  - type: web
    name: pokemon-card-tracker
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: POKEMON_TCG_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: ["*"]
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1 